spring:
  redis:
    host: ${demo.redis.host}
    port: ${demo.redis.port}
    password: ${demo.redis.password}
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 10000
        # 连接池中的最大空闲连接 默认 8
        max-idle: 20
        # 连接池中的最小空闲连接 默认 0
        min-idle: 10
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: test
      time-to-live: 200
